language: android
android:
  components:
    - tools
    - build-tools-19.1.0
    - android-19
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - android-sdk-license-bcbbd656
    - android-sdk-license-5be876d5
    - android-sdk-license-598b93a6
    - android-sdk-preview-license-52d11cd2
