language: android
android:
  components:
    - platform-tools
    - build-tools-19.1.0
    - android-19
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - android-sdk-license-bcbbd656

install:
    - ./gradlew assemble --info --stacktrace
